name: UAT - Build and Deploy Angular App

on:
  push:
    branches:
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop # Specify the branch to use

      - name: Get commit message
        id: commit_message
        #run: echo "::set-output name=message::$(git log -1 --pretty=%B)"
        run: echo "message=$(git log -1 --pretty=%B | sed ':a;N;$!ba;s/\n/ /g')" >> $GITHUB_OUTPUT

      - name: Get commit hash
        id: commit_hash
        #run: echo "::set-output name=hash::$(git log -1 --pretty=%H)"
        run: echo "hash=$(git log -1 --pretty=%H | sed ':a;N;$!ba;s/\n/ /g')" >> $GITHUB_OUTPUT

      - name: Get current time
        id: build_time
        #run: echo "::set-output name=time::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        run: echo "time=$(date -u +'%Y-%m-%dT%H:%M:%SZ' | sed ':a;N;$!ba;s/\n/ /g')" >> $GITHUB_OUTPUT

      - name: Create info.html
        run: |
          echo "Commit message: ${{ steps.commit_message.outputs.message }}<br>" > info.html
          echo "Commit hash: ${{ steps.commit_hash.outputs.hash }}<br>" >> info.html
          echo "Build time: ${{ steps.build_time.outputs.time }}" >> info.html

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use the Node.js version your project requires

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      #- name: Clean install dependencies
      #        run: |
      #          rm -rf node_modules
      #          rm -f package-lock.json
      #          npm install

      # Install dependencies with npm ci
      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build
        #builddev

      - name: Copy info.html to dist folder
        run: cp info.html dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.MASTER_TOKEN }}
          publish_dir: ./dist
